default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default
test:
  <<: *default